CREATE SNAPSHOT TABLE `${DATASET}.t_snap` CLONE `${DATASET}.t`;
DROP SNAPSHOT TABLE `${DATASET}.t_snap`;
INSERT INTO `${DATASET}.t` VALUES (3, "c"), (4, "d");
CREATE SNAPSHOT TABLE `${DATASET}.t_snap` CLONE `${DATASET}.t`;
SELECT id, label FROM `${DATASET}.t_snap` ORDER BY id
