CREATE OR REPLACE TABLE `${DATASET}.orders` (id INT64, country STRING, amount NUMERIC) AS
SELECT 1 AS id, 'US' AS country, NUMERIC '100.00' AS amount UNION ALL
SELECT 2, 'EU', NUMERIC '200.50' UNION ALL
SELECT 3, 'JP', NUMERIC '300.75';
