CREATE OR REPLACE TABLE `${DATASET}.events_20240101` AS SELECT 1 AS id, "click" AS event;
CREATE OR REPLACE TABLE `${DATASET}.events_20240102` AS SELECT 2 AS id, "view" AS event;
CREATE OR REPLACE TABLE `${DATASET}.events_20240103` AS SELECT 3 AS id, "purchase" AS event;
CREATE OR REPLACE TABLE `${DATASET}.events_20240201` AS SELECT 4 AS id, "click" AS event;
CREATE OR REPLACE TABLE `${DATASET}.events_20240202` AS SELECT 5 AS id, "view" AS event;
