CREATE OR REPLACE TABLE `${DATASET}.c` CLONE `${DATASET}.t`;
DELETE FROM `${DATASET}.t` WHERE id IN (1, 3);
INSERT INTO `${DATASET}.t` VALUES (5, "e");
SELECT id, label FROM `${DATASET}.c` ORDER BY id
