"""Canonical inventory of BigQuery surface items the conformance corpus targets.

This module is the single source of truth for the
:doc:`docs/reference/conformance-coverage-matrix.md` document, which is
generated by :mod:`scripts.generate_coverage_matrix`. Every item here is
a *thing the emulator must match BigQuery on*, mapped to a detection
pattern the generator uses to scan ``tests/conformance/sql_corpus/`` for
fixtures that exercise it.

The inventory is intentionally coarse-grained: one entry per BQ surface
concept (function, statement type, type-system surface, REST resource,
error reason), not per (concept x edge-case). The depth tier columns in
the generated matrix (``Uncovered`` / ``Sampled`` / ``Covered`` /
``Deep``) communicate per-concept depth without requiring the inventory
to enumerate every (NULL x empty x overflow x type-variant) sub-cell.
That keeps maintenance cost linear in BQ's public surface size rather
than quadratic.

Adding an item: append it to the relevant
:class:`SurfaceCategory.items` tuple, with a stable ``id``, a
``detect`` pattern (compiled regex or callable), and a ``bq_docs`` URL.
The generator picks it up automatically on the next run.
"""

from __future__ import annotations

from dataclasses import dataclass
import re


@dataclass(frozen=True)
class SurfaceItem:
    """One element of BigQuery's public surface that conformance must cover."""

    id: str
    """Stable identifier: ``<category-id>.<item-id>``."""

    name: str
    """Human-readable name. Used as the row label in the matrix."""

    bq_docs: str
    """BigQuery documentation anchor for this item."""

    detect: re.Pattern[str]
    """Regex (case-insensitive, multiline) that, when found in any
    ``query.sql`` or ``setup.sql`` of a fixture, marks that fixture as
    exercising this surface item. Use word boundaries (``\\b``) on
    function and statement names to avoid substring false positives."""

    notes: str = ""
    """Optional clarifier — e.g. "matches BQ's ``ARRAY_AGG`` not
    DuckDB's ``LIST``" or "applies to both the SQL form and the
    REST tables.insert form"."""

    nondeterministic: bool = False
    """Set ``True`` for surface items inherently excluded from the
    conformance corpus by :doc:`docs/adr/0022-conformance-corpus-design`
    §1.2 / §7 (wall-clock, RNG, session state, or sampling whose output
    cannot be reproduced fixture-to-fixture). The matrix generator
    treats these items as a permanent exclusion — they don't pollute
    the gap-table count and are surfaced under a separate
    "Excluded (non-deterministic)" summary subsection with a note
    explaining where the surface IS exercised (property tests,
    integration tier, unit tier)."""


@dataclass(frozen=True)
class SurfaceCategory:
    """A group of related surface items (e.g. all string functions)."""

    id: str
    """Stable category identifier, used in matrix anchors."""

    name: str
    """Human-readable category name."""

    bq_docs: str
    """Category-level BQ documentation URL."""

    items: tuple[SurfaceItem, ...]
    """The items in this category, in matrix-display order."""

    description: str = ""
    """Optional one-paragraph blurb shown above the category's matrix
    table. Use for "what this category exercises and why it matters"."""


def _re(pattern: str) -> re.Pattern[str]:
    """Compile a case-insensitive multiline regex.

    Convenience wrapper so item literals don't repeat
    ``re.compile(..., re.IGNORECASE | re.MULTILINE)``.
    """
    return re.compile(pattern, re.IGNORECASE | re.MULTILINE)


def _fn(name: str) -> re.Pattern[str]:
    """Compile a function-call detector regex.

    ``\\b<NAME>\\s*\\(`` matches the function-call form without
    matching substrings (``LENGTH`` inside ``CHAR_LENGTH``) or column
    references (``LENGTH`` as a bare identifier). Tightens detection
    versus a bare-word regex.
    """
    return _re(rf"\b{re.escape(name)}\s*\(")


def _kw(name: str) -> re.Pattern[str]:
    """Compile a keyword detector regex (no opening paren expected)."""
    return _re(rf"\b{re.escape(name)}\b")


# ---------------------------------------------------------------------------
# DML statements
# ---------------------------------------------------------------------------
DML = SurfaceCategory(
    id="dml",
    name="Data Manipulation (DML)",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax",
    description=(
        "BigQuery's DML statements. Coverage must include happy-path + "
        "rows-affected reporting + interaction with row-access policies "
        "(per ADR 0018) and time-travel snapshots (per ADR 0016)."
    ),
    items=(
        SurfaceItem(
            id="dml.insert_values",
            name="INSERT … VALUES",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#insert_statement",
            detect=_re(r"\binsert\s+into\b[^;]*?\bvalues\b"),
        ),
        SurfaceItem(
            id="dml.insert_select",
            name="INSERT … SELECT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#insert_statement",
            detect=_re(r"\binsert\s+into\b[^;]*?\bselect\b"),
        ),
        SurfaceItem(
            id="dml.update",
            name="UPDATE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#update_statement",
            detect=_kw("UPDATE"),
        ),
        SurfaceItem(
            id="dml.update_from",
            name="UPDATE … FROM",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#update_statement",
            detect=_re(r"\bupdate\b[^;]*?\bset\b[^;]*?\bfrom\b"),
        ),
        SurfaceItem(
            id="dml.delete",
            name="DELETE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#delete_statement",
            detect=_re(r"\bdelete\s+from\b"),
        ),
        SurfaceItem(
            id="dml.merge",
            name="MERGE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#merge_statement",
            detect=_re(r"\bmerge\s+(?:into\s+)?"),
        ),
        SurfaceItem(
            id="dml.truncate",
            name="TRUNCATE TABLE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#truncate_table_statement",
            detect=_re(r"\btruncate\s+table\b"),
        ),
    ),
)

# ---------------------------------------------------------------------------
# DDL statements
# ---------------------------------------------------------------------------
DDL = SurfaceCategory(
    id="ddl",
    name="Data Definition (DDL)",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language",
    description=(
        "Schema-mutating DDL. Each form has wire-format implications "
        "(REST tables.insert / tables.patch / tables.delete) — coverage "
        "should pair the SQL form with the REST equivalent where BQ "
        "publishes both."
    ),
    items=(
        SurfaceItem(
            id="ddl.create_table",
            name="CREATE TABLE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?table\b(?!\s+(?:snapshot|clone))"),
        ),
        SurfaceItem(
            id="ddl.create_table_as_select",
            name="CREATE TABLE … AS SELECT (CTAS)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?table\b[^;]*?\bas\b[^;]*?\bselect\b"),
        ),
        SurfaceItem(
            id="ddl.create_table_schema",
            name="CREATE TABLE … (schema) AS SELECT (combined)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?table\b\s+\S+\s*\([^)]*\)\s*as\s+select"),
            notes=("Combined form requires the CTAS-with-schema rewriter (closed 2026-05-18)."),
        ),
        SurfaceItem(
            id="ddl.create_view",
            name="CREATE VIEW",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_view_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?view\b"),
        ),
        SurfaceItem(
            id="ddl.create_materialized_view",
            name="CREATE MATERIALIZED VIEW",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_materialized_view_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?materialized\s+view\b"),
        ),
        SurfaceItem(
            id="ddl.refresh_mv",
            name="REFRESH MATERIALIZED VIEW / CALL BQ.REFRESH_MATERIALIZED_VIEW",
            bq_docs="https://cloud.google.com/bigquery/docs/materialized-views-manage#refresh",
            detect=_re(r"\b(refresh\s+materialized\s+view|bq\.refresh_materialized_view)\b"),
        ),
        SurfaceItem(
            id="ddl.create_snapshot",
            name="CREATE SNAPSHOT TABLE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_snapshot_table_statement",
            detect=_re(r"\bcreate\s+snapshot\s+table\b"),
        ),
        SurfaceItem(
            id="ddl.create_clone",
            name="CREATE TABLE … CLONE",
            bq_docs="https://cloud.google.com/bigquery/docs/table-clones-create",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?table\b[^;]*?\bclone\b"),
        ),
        SurfaceItem(
            id="ddl.drop_table",
            name="DROP TABLE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_table_statement",
            detect=_re(r"\bdrop\s+table\b"),
        ),
        SurfaceItem(
            id="ddl.drop_view",
            name="DROP VIEW",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_view_statement",
            detect=_re(r"\bdrop\s+view\b"),
        ),
        SurfaceItem(
            id="ddl.drop_mv",
            name="DROP MATERIALIZED VIEW",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_materialized_view_statement",
            detect=_re(r"\bdrop\s+materialized\s+view\b"),
        ),
        SurfaceItem(
            id="ddl.drop_snapshot",
            name="DROP SNAPSHOT TABLE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_snapshot_table_statement",
            detect=_re(r"\bdrop\s+snapshot\s+table\b"),
        ),
        SurfaceItem(
            id="ddl.alter_table_add_column",
            name="ALTER TABLE ADD COLUMN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_add_column_statement",
            detect=_re(r"\balter\s+table\b[^;]*?\badd\s+column\b"),
        ),
        SurfaceItem(
            id="ddl.alter_table_drop_column",
            name="ALTER TABLE DROP COLUMN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_column_statement",
            detect=_re(r"\balter\s+table\b[^;]*?\bdrop\s+column\b"),
        ),
        SurfaceItem(
            id="ddl.alter_table_rename",
            name="ALTER TABLE RENAME",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_rename_to_statement",
            detect=_re(r"\balter\s+table\b[^;]*?\brename\s+to\b"),
        ),
        SurfaceItem(
            id="ddl.create_function",
            name="CREATE FUNCTION (SQL UDF)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement",
            detect=_re(r"\bcreate\s+(?:temp(?:orary)?\s+)?(?:or\s+replace\s+)?function\b"),
        ),
        SurfaceItem(
            id="ddl.create_function_js",
            name="CREATE FUNCTION (JS UDF)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/user-defined-functions",
            detect=_re(r"\blanguage\s+(?:js|javascript)\b"),
        ),
        SurfaceItem(
            id="ddl.create_table_function",
            name="CREATE TABLE FUNCTION (TVF)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_function_statement",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?table\s+function\b"),
        ),
        SurfaceItem(
            id="ddl.create_procedure",
            name="CREATE PROCEDURE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_procedure",
            detect=_re(r"\bcreate\s+(?:or\s+replace\s+)?procedure\b"),
        ),
        SurfaceItem(
            id="ddl.create_row_access_policy",
            name="CREATE ROW ACCESS POLICY (REST)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/rowAccessPolicies/insert",
            detect=_re(r"rowAccessPolicies"),
            notes="Setup happens via setup_rest.json POST, not SQL.",
        ),
    ),
)

# ---------------------------------------------------------------------------
# Query language — set operations, joins, subqueries, window functions
# ---------------------------------------------------------------------------
QUERY = SurfaceCategory(
    id="query",
    name="Query language",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax",
    description=(
        "Composite SELECT shapes (joins, set ops, subqueries, window "
        "functions). Coverage depth here drives confidence that the "
        "translator handles real-world analytical queries."
    ),
    items=(
        SurfaceItem(
            id="query.select",
            name="SELECT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_list",
            detect=_kw("SELECT"),
        ),
        SurfaceItem(
            id="query.where",
            name="WHERE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#where_clause",
            detect=_re(r"\bwhere\b"),
        ),
        SurfaceItem(
            id="query.group_by",
            name="GROUP BY",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#group_by_clause",
            detect=_re(r"\bgroup\s+by\b"),
        ),
        SurfaceItem(
            id="query.having",
            name="HAVING",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#having_clause",
            detect=_re(r"\bhaving\b"),
        ),
        SurfaceItem(
            id="query.qualify",
            name="QUALIFY",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#qualify_clause",
            detect=_re(r"\bqualify\b"),
        ),
        SurfaceItem(
            id="query.order_by",
            name="ORDER BY",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#order_by_clause",
            detect=_re(r"\border\s+by\b"),
        ),
        SurfaceItem(
            id="query.limit",
            name="LIMIT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#limit_and_offset_clause",
            detect=_re(r"\blimit\b\s+\d"),
        ),
        SurfaceItem(
            id="query.offset",
            name="OFFSET",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#limit_and_offset_clause",
            detect=_re(r"\boffset\b\s+\d"),
        ),
        SurfaceItem(
            id="query.distinct",
            name="SELECT DISTINCT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_distinct",
            detect=_re(r"\bselect\s+distinct\b"),
        ),
        SurfaceItem(
            id="query.union_all",
            name="UNION ALL",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators",
            detect=_re(r"\bunion\s+all\b"),
        ),
        SurfaceItem(
            id="query.union_distinct",
            name="UNION DISTINCT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators",
            detect=_re(r"\bunion\s+distinct\b"),
        ),
        SurfaceItem(
            id="query.intersect",
            name="INTERSECT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators",
            detect=_re(r"\bintersect\s+(?:all|distinct)\b"),
        ),
        SurfaceItem(
            id="query.except",
            name="EXCEPT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#set_operators",
            detect=_re(r"\bexcept\s+(?:all|distinct)\b"),
        ),
        SurfaceItem(
            id="query.inner_join",
            name="INNER JOIN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#inner_join",
            detect=_re(r"\b(?:inner\s+)?join\b(?!\s+(?:left|right|full|cross))"),
        ),
        SurfaceItem(
            id="query.left_join",
            name="LEFT JOIN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#left_outer_join",
            detect=_re(r"\bleft\s+(?:outer\s+)?join\b"),
        ),
        SurfaceItem(
            id="query.right_join",
            name="RIGHT JOIN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#right_outer_join",
            detect=_re(r"\bright\s+(?:outer\s+)?join\b"),
        ),
        SurfaceItem(
            id="query.full_join",
            name="FULL OUTER JOIN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#full_outer_join",
            detect=_re(r"\bfull\s+(?:outer\s+)?join\b"),
        ),
        SurfaceItem(
            id="query.cross_join",
            name="CROSS JOIN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#cross_join",
            detect=_re(r"\bcross\s+join\b"),
        ),
        SurfaceItem(
            id="query.unnest",
            name="UNNEST",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unnest_operator",
            detect=_fn("UNNEST"),
        ),
        SurfaceItem(
            id="query.with_cte",
            name="WITH (CTE)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#with_clause",
            detect=_re(r"\bwith\b\s+\w+\s+as\b"),
        ),
        SurfaceItem(
            id="query.recursive_cte",
            name="WITH RECURSIVE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#recursive_cte",
            detect=_re(r"\bwith\s+recursive\b"),
        ),
        SurfaceItem(
            id="query.window_over",
            name="Window functions (OVER)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/window-function-calls",
            detect=_re(r"\bover\s*\("),
        ),
        SurfaceItem(
            id="query.case_when",
            name="CASE WHEN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/conditional_expressions#case_when",
            detect=_re(r"\bcase\s+when\b"),
        ),
        SurfaceItem(
            id="query.exists",
            name="EXISTS",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/expression_subqueries#exists_subquery",
            detect=_re(r"\bexists\s*\("),
        ),
        SurfaceItem(
            id="query.in_subquery",
            name="IN (subquery)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/expression_subqueries#in_subquery",
            detect=_re(r"\bin\s*\(\s*select\b"),
        ),
        SurfaceItem(
            id="query.wildcard_table",
            name="Wildcard tables (`prefix_*`)",
            bq_docs="https://cloud.google.com/bigquery/docs/querying-wildcard-tables",
            detect=_re(r"`[^`]*\*[^`]*`"),
        ),
        SurfaceItem(
            id="query.table_suffix",
            name="_TABLE_SUFFIX pseudo-column",
            bq_docs="https://cloud.google.com/bigquery/docs/querying-wildcard-tables#filtering_selected_tables_using_table_suffix",
            detect=_kw("_TABLE_SUFFIX"),
        ),
        SurfaceItem(
            id="query.partition_pruning",
            name="Partition pruning (WHERE on partition col)",
            bq_docs="https://cloud.google.com/bigquery/docs/partitioned-tables",
            detect=_re(r"\b(_PARTITIONDATE|_PARTITIONTIME)\b"),
        ),
        SurfaceItem(
            id="query.for_system_time_as_of",
            name="FOR SYSTEM_TIME AS OF (time travel)",
            bq_docs="https://cloud.google.com/bigquery/docs/time-travel",
            detect=_re(r"\bfor\s+system_time\s+as\s+of\b"),
            nondeterministic=True,
            notes=(
                "Excluded from the conformance corpus by ADR 0022 §7 — "
                "the relative-timestamp form depends on wall-clock state. "
                "A literal-pinned-timestamp variant is deferred per the "
                "P2.c closure note. Dynamic time-travel is exercised at "
                "the integration tier (tests/integration/test_time_travel.py)."
            ),
        ),
        SurfaceItem(
            id="query.tablesample",
            name="TABLESAMPLE",
            bq_docs="https://cloud.google.com/bigquery/docs/table-sampling",
            detect=_re(r"\btablesample\s+system\b"),
            nondeterministic=True,
            notes=(
                "Excluded from the conformance corpus by ADR 0022 §1.2 — "
                "TABLESAMPLE SYSTEM is non-deterministic (random sampling). "
                "Shape-only coverage lives in unit / integration tiers."
            ),
        ),
        SurfaceItem(
            id="query.pivot",
            name="PIVOT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#pivot_operator",
            detect=_kw("PIVOT"),
        ),
        SurfaceItem(
            id="query.unpivot",
            name="UNPIVOT",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unpivot_operator",
            detect=_kw("UNPIVOT"),
        ),
    ),
)

# ---------------------------------------------------------------------------
# Scripting (BEGIN/END, DECLARE, IF, WHILE, FOR, CALL, EXECUTE IMMEDIATE)
# ---------------------------------------------------------------------------
SCRIPTING = SurfaceCategory(
    id="scripting",
    name="Procedural scripting",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language",
    description=(
        "Multi-statement scripting features — the interpreter at "
        "src/bqemulator/scripting/interpreter.py."
    ),
    items=(
        SurfaceItem(
            id="scripting.declare",
            name="DECLARE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#declare",
            detect=_re(r"\bdeclare\b"),
        ),
        SurfaceItem(
            id="scripting.set",
            name="SET (script variable)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#set",
            detect=_re(r"\bset\s+\w+\s*="),
        ),
        SurfaceItem(
            id="scripting.if",
            name="IF / ELSEIF / ELSE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#if",
            detect=_re(r"\bif\b[^;]*?\bthen\b"),
        ),
        SurfaceItem(
            id="scripting.while",
            name="WHILE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#while",
            detect=_re(r"\bwhile\b[^;]*?\bdo\b"),
        ),
        SurfaceItem(
            id="scripting.loop",
            name="LOOP",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#loop",
            detect=_re(r"^\s*loop\b"),
        ),
        SurfaceItem(
            id="scripting.for",
            name="FOR (loop)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#for_in",
            detect=_re(r"\bfor\b[^;]*?\bin\b[^;]*?\bdo\b"),
        ),
        SurfaceItem(
            id="scripting.break_continue",
            name="BREAK / CONTINUE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#break",
            detect=_re(r"\b(break|continue|leave|iterate)\b"),
        ),
        SurfaceItem(
            id="scripting.begin_end",
            name="BEGIN … END (block)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#beginend",
            detect=_re(r"\bbegin\b(?!\s+transaction)"),
        ),
        SurfaceItem(
            id="scripting.exception",
            name="BEGIN … EXCEPTION WHEN ERROR",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#beginexception",
            detect=_re(r"\bexception\s+when\s+error\b"),
        ),
        SurfaceItem(
            id="scripting.raise",
            name="RAISE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#raise",
            detect=_re(r"\braise\b"),
        ),
        SurfaceItem(
            id="scripting.call",
            name="CALL (procedure)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#call",
            detect=_re(r"^\s*call\b"),
        ),
        SurfaceItem(
            id="scripting.execute_immediate",
            name="EXECUTE IMMEDIATE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#execute_immediate",
            detect=_re(r"\bexecute\s+immediate\b"),
        ),
        SurfaceItem(
            id="scripting.return",
            name="RETURN",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#return",
            detect=_re(r"\breturn\b"),
        ),
        SurfaceItem(
            id="scripting.begin_transaction",
            name="BEGIN TRANSACTION / COMMIT / ROLLBACK",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/transactions",
            detect=_re(r"\b(begin\s+transaction|commit\s+transaction|rollback\s+transaction)\b"),
        ),
    ),
)

# ---------------------------------------------------------------------------
# Data types — coverage by type-system surface
# ---------------------------------------------------------------------------
TYPES = SurfaceCategory(
    id="types",
    name="Data types",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types",
    description=(
        "Every BigQuery scalar + compound type. Coverage should "
        "exercise the type as a column type, in a literal, and through "
        "CAST."
    ),
    items=(
        SurfaceItem(
            id="types.int64",
            name="INT64",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#integer_type",
            detect=_re(r"\bint64\b"),
        ),
        SurfaceItem(
            id="types.float64",
            name="FLOAT64",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#floating_point_types",
            detect=_re(r"\bfloat64\b"),
        ),
        SurfaceItem(
            id="types.numeric",
            name="NUMERIC",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types",
            detect=_re(r"\bnumeric\b"),
        ),
        SurfaceItem(
            id="types.bignumeric",
            name="BIGNUMERIC",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types",
            detect=_re(r"\bbignumeric\b"),
        ),
        SurfaceItem(
            id="types.bool",
            name="BOOL",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#boolean_type",
            detect=_re(r"\bbool\b"),
        ),
        SurfaceItem(
            id="types.string",
            name="STRING",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#string_type",
            detect=_re(r"\bstring\b"),
        ),
        SurfaceItem(
            id="types.bytes",
            name="BYTES",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#bytes_type",
            detect=_re(r"\bbytes\b"),
        ),
        SurfaceItem(
            id="types.date",
            name="DATE",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#date_type",
            detect=_re(r"\bdate\b"),
        ),
        SurfaceItem(
            id="types.time",
            name="TIME",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#time_type",
            detect=_re(r"\btime\b"),
        ),
        SurfaceItem(
            id="types.datetime",
            name="DATETIME",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#datetime_type",
            detect=_re(r"\bdatetime\b"),
        ),
        SurfaceItem(
            id="types.timestamp",
            name="TIMESTAMP",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp_type",
            detect=_re(r"\btimestamp\b"),
        ),
        SurfaceItem(
            id="types.interval",
            name="INTERVAL",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#interval_type",
            detect=_re(r"\binterval\b"),
        ),
        SurfaceItem(
            id="types.range",
            name="RANGE<T>",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#range_type",
            detect=_re(r"\brange\s*<"),
        ),
        SurfaceItem(
            id="types.geography",
            name="GEOGRAPHY",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#geography_type",
            detect=_re(r"\bgeography\b"),
        ),
        SurfaceItem(
            id="types.json",
            name="JSON",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#json_type",
            detect=_re(r"\bjson\b"),
        ),
        SurfaceItem(
            id="types.array",
            name="ARRAY<T>",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#array_type",
            detect=_re(r"\barray\s*<"),
        ),
        SurfaceItem(
            id="types.struct",
            name="STRUCT<...>",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#struct_type",
            detect=_re(r"\bstruct\s*<"),
        ),
    ),
)

# ---------------------------------------------------------------------------
# Function categories — built-ins. Each item is one function.
# ---------------------------------------------------------------------------
FUNCTIONS_STRING = SurfaceCategory(
    id="functions_string",
    name="String functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_string.{name.lower()}",
            name=name,
            bq_docs=f"https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#{name.lower()}",
            detect=_fn(name),
        )
        for name in (
            "ASCII",
            "BYTE_LENGTH",
            "CHAR_LENGTH",
            "CHR",
            "CODE_POINTS_TO_BYTES",
            "CODE_POINTS_TO_STRING",
            "COLLATE",
            "CONCAT",
            "CONTAINS_SUBSTR",
            "ENDS_WITH",
            "FORMAT",
            "FROM_BASE32",
            "FROM_BASE64",
            "FROM_HEX",
            "INITCAP",
            "INSTR",
            "LEFT",
            "LENGTH",
            "LOWER",
            "LPAD",
            "LTRIM",
            "NORMALIZE",
            "NORMALIZE_AND_CASEFOLD",
            "OCTET_LENGTH",
            "REGEXP_CONTAINS",
            "REGEXP_EXTRACT",
            "REGEXP_EXTRACT_ALL",
            "REGEXP_INSTR",
            "REGEXP_REPLACE",
            "REGEXP_SUBSTR",
            "REPEAT",
            "REPLACE",
            "REVERSE",
            "RIGHT",
            "RPAD",
            "RTRIM",
            "SAFE_CONVERT_BYTES_TO_STRING",
            "SOUNDEX",
            "SPLIT",
            "STARTS_WITH",
            "STRPOS",
            "SUBSTR",
            "SUBSTRING",
            "TO_BASE32",
            "TO_BASE64",
            "TO_CODE_POINTS",
            "TO_HEX",
            "TRANSLATE",
            "TRIM",
            "UNICODE",
            "UPPER",
        )
    ),
)

_NONDETERMINISTIC_NUMERIC: dict[str, str] = {
    "RAND": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 — "
        "RAND() is non-deterministic. The function is property-tested "
        "via Hypothesis (uniformity, range bounds)."
    ),
}

FUNCTIONS_NUMERIC = SurfaceCategory(
    id="functions_numeric",
    name="Numeric / math functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_numeric.{name.lower()}",
            name=name,
            bq_docs=f"https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#{name.lower()}",
            detect=_fn(name),
            nondeterministic=name in _NONDETERMINISTIC_NUMERIC,
            notes=_NONDETERMINISTIC_NUMERIC.get(name, ""),
        )
        for name in (
            "ABS",
            "ACOS",
            "ACOSH",
            "ASIN",
            "ASINH",
            "ATAN",
            "ATAN2",
            "ATANH",
            "CBRT",
            "CEIL",
            "CEILING",
            "COS",
            "COSH",
            "COT",
            "COTH",
            "CSC",
            "CSCH",
            "DIV",
            "EXP",
            "FLOOR",
            "GREATEST",
            "IEEE_DIVIDE",
            "IS_INF",
            "IS_NAN",
            "LEAST",
            "LN",
            "LOG",
            "LOG10",
            "MOD",
            "POW",
            "POWER",
            "RAND",
            "RANGE_BUCKET",
            "ROUND",
            "SAFE_ADD",
            "SAFE_DIVIDE",
            "SAFE_MULTIPLY",
            "SAFE_NEGATE",
            "SAFE_SUBTRACT",
            "SEC",
            "SECH",
            "SIGN",
            "SIN",
            "SINH",
            "SQRT",
            "TAN",
            "TANH",
            "TRUNC",
        )
    ),
)

FUNCTIONS_AGGREGATE = SurfaceCategory(
    id="functions_aggregate",
    name="Aggregate functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_aggregate.{name.lower()}",
            name=name,
            bq_docs=f"https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions#{name.lower()}",
            detect=_fn(name),
        )
        for name in (
            "ANY_VALUE",
            "ARRAY_AGG",
            "ARRAY_CONCAT_AGG",
            "AVG",
            "BIT_AND",
            "BIT_OR",
            "BIT_XOR",
            "COUNT",
            "COUNTIF",
            "GROUPING",
            "LOGICAL_AND",
            "LOGICAL_OR",
            "MAX",
            "MAX_BY",
            "MIN",
            "MIN_BY",
            "STRING_AGG",
            "SUM",
            "CORR",
            "COVAR_POP",
            "COVAR_SAMP",
            "STDDEV",
            "STDDEV_POP",
            "STDDEV_SAMP",
            "VAR_POP",
            "VAR_SAMP",
            "VARIANCE",
            "APPROX_COUNT_DISTINCT",
            "APPROX_QUANTILES",
            "APPROX_TOP_COUNT",
            "APPROX_TOP_SUM",
            "HLL_COUNT.INIT",
            "HLL_COUNT.MERGE",
            "HLL_COUNT.MERGE_PARTIAL",
            "HLL_COUNT.EXTRACT",
        )
    ),
)

_NONDETERMINISTIC_DATETIME: dict[str, str] = {
    "CURRENT_DATE": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 / §7 — "
        "wall-clock dependent. Static-date queries are exercised "
        "indirectly via DATE_ADD/DATE_SUB fixtures."
    ),
    "CURRENT_DATETIME": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 / §7 — wall-clock dependent."
    ),
    "CURRENT_TIME": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 / §7 — wall-clock dependent."
    ),
    "CURRENT_TIMESTAMP": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 / §7 — "
        "wall-clock dependent. The function is exercised in unit / "
        "integration tiers where the harness pins time."
    ),
}

FUNCTIONS_DATETIME = SurfaceCategory(
    id="functions_datetime",
    name="Date / time / timestamp / datetime functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_datetime.{name.lower().replace('.', '_')}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions",
            detect=_fn(name),
            nondeterministic=name in _NONDETERMINISTIC_DATETIME,
            notes=_NONDETERMINISTIC_DATETIME.get(name, ""),
        )
        for name in (
            "CURRENT_DATE",
            "CURRENT_DATETIME",
            "CURRENT_TIME",
            "CURRENT_TIMESTAMP",
            "DATE",
            "DATETIME",
            "DATE_ADD",
            "DATE_DIFF",
            "DATE_FROM_UNIX_DATE",
            "DATE_SUB",
            "DATE_TRUNC",
            "DATETIME_ADD",
            "DATETIME_DIFF",
            "DATETIME_SUB",
            "DATETIME_TRUNC",
            "EXTRACT",
            "FORMAT_DATE",
            "FORMAT_DATETIME",
            "FORMAT_TIME",
            "FORMAT_TIMESTAMP",
            "GENERATE_DATE_ARRAY",
            "GENERATE_TIMESTAMP_ARRAY",
            "LAST_DAY",
            "PARSE_DATE",
            "PARSE_DATETIME",
            "PARSE_TIME",
            "PARSE_TIMESTAMP",
            "TIME",
            "TIME_ADD",
            "TIME_DIFF",
            "TIME_SUB",
            "TIME_TRUNC",
            "TIMESTAMP",
            "TIMESTAMP_ADD",
            "TIMESTAMP_DIFF",
            # ``TIMESTAMP_FROM_UNIX_MILLIS`` removed 2026-05-18: real
            # BigQuery returns "Function TIMESTAMP_FROM_UNIX_MILLIS is
            # not yet implemented" for any call, so no fixture can be
            # recorded against the live service. ``TIMESTAMP_MILLIS``
            # below covers the equivalent epoch-millis conversion that
            # users reach for in practice.
            "TIMESTAMP_MICROS",
            "TIMESTAMP_MILLIS",
            "TIMESTAMP_SECONDS",
            "TIMESTAMP_SUB",
            "TIMESTAMP_TRUNC",
            "UNIX_DATE",
            "UNIX_MICROS",
            "UNIX_MILLIS",
            "UNIX_SECONDS",
        )
    ),
)

FUNCTIONS_ARRAY = SurfaceCategory(
    id="functions_array",
    name="Array functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_array.{name.lower()}",
            name=name,
            bq_docs=f"https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#{name.lower()}",
            detect=_fn(name),
        )
        for name in (
            "ARRAY",
            "ARRAY_CONCAT",
            "ARRAY_LENGTH",
            "ARRAY_REVERSE",
            "ARRAY_TO_STRING",
            "GENERATE_ARRAY",
            "ARRAY_FIRST",
            "ARRAY_LAST",
            # ARRAY_INCLUDES / ARRAY_INCLUDES_ANY / ARRAY_INCLUDES_ALL are
            # listed in the BigQuery reference docs but return
            # ``Function ARRAY_INCLUDES[_ANY|_ALL] is not yet implemented.``
            # against the live service (probed 2026-05-18). Following the
            # TIMESTAMP_FROM_UNIX_MILLIS precedent from top-30 session #2
            # we omit them from the inventory until BigQuery ships them so
            # the gap-target denominator stays actionable.
            "OFFSET",
            "ORDINAL",
            "SAFE_OFFSET",
            "SAFE_ORDINAL",
        )
    ),
)

FUNCTIONS_JSON = SurfaceCategory(
    id="functions_json",
    name="JSON functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_json.{name.lower().replace('.', '_')}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/json_functions",
            detect=_fn(name),
        )
        for name in (
            "JSON_EXTRACT",
            "JSON_EXTRACT_SCALAR",
            "JSON_EXTRACT_ARRAY",
            "JSON_EXTRACT_STRING_ARRAY",
            "JSON_QUERY",
            "JSON_QUERY_ARRAY",
            "JSON_VALUE",
            "JSON_VALUE_ARRAY",
            "JSON_TYPE",
            "JSON_OBJECT",
            "JSON_ARRAY",
            "JSON_ARRAY_INSERT",
            "JSON_REMOVE",
            "JSON_SET",
            "JSON_STRIP_NULLS",
            "JSON_KEYS",
            "PARSE_JSON",
            "TO_JSON",
            "TO_JSON_STRING",
            "BOOL",
            "FLOAT64",
            "INT64",
            "STRING",
            "LAX_BOOL",
            "LAX_FLOAT64",
            "LAX_INT64",
            "LAX_STRING",
        )
    ),
)

FUNCTIONS_GEOGRAPHY = SurfaceCategory(
    id="functions_geography",
    name="GEOGRAPHY functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions",
    description=(
        "Spheroidal-vs-planar divergences here are documented in "
        "ADR 0019 and out-of-scope.md (continental-scale comparisons "
        "are pinned as expected mismatches)."
    ),
    items=tuple(
        SurfaceItem(
            id=f"functions_geography.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/geography_functions",
            detect=_fn(name),
        )
        for name in (
            "ST_GEOGPOINT",
            "ST_GEOGFROMTEXT",
            "ST_GEOGFROMGEOJSON",
            "ST_GEOGFROMWKB",
            "ST_ASTEXT",
            "ST_ASGEOJSON",
            "ST_ASBINARY",
            "ST_BOUNDARY",
            "ST_CENTROID",
            "ST_CLOSESTPOINT",
            "ST_CLUSTERDBSCAN",
            "ST_CONVEXHULL",
            "ST_DIFFERENCE",
            "ST_DUMP",
            "ST_DWITHIN",
            "ST_DIMENSION",
            "ST_DISJOINT",
            "ST_DISTANCE",
            "ST_EQUALS",
            "ST_INTERSECTION",
            "ST_INTERSECTS",
            "ST_INTERSECTSBOX",
            "ST_ISCLOSED",
            "ST_ISCOLLECTION",
            "ST_ISEMPTY",
            "ST_ISRING",
            "ST_LENGTH",
            "ST_MAKELINE",
            "ST_MAKEPOLYGON",
            "ST_MAKEPOLYGONORIENTED",
            "ST_MAXDISTANCE",
            "ST_NPOINTS",
            "ST_PERIMETER",
            "ST_POINTN",
            "ST_SIMPLIFY",
            "ST_SNAPTOGRID",
            "ST_TOUCHES",
            "ST_UNION",
            "ST_UNION_AGG",
            "ST_WITHIN",
            "ST_X",
            "ST_Y",
            "ST_AREA",
            "ST_BUFFER",
            "ST_CONTAINS",
            "ST_COVERS",
            "ST_COVEREDBY",
        )
    ),
)

FUNCTIONS_CONVERSION = SurfaceCategory(
    id="functions_conversion",
    name="Conversion / type functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_conversion.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/conversion_functions",
            detect=_fn(name),
        )
        for name in (
            "CAST",
            "SAFE_CAST",
            "PARSE_NUMERIC",
            "PARSE_BIGNUMERIC",
        )
    ),
)

FUNCTIONS_CONDITIONAL = SurfaceCategory(
    id="functions_conditional",
    name="Conditional functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/conditional_expressions",
    items=tuple(
        SurfaceItem(
            id=f"functions_conditional.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/conditional_expressions",
            detect=_fn(name),
        )
        for name in (
            "COALESCE",
            "IF",
            "IFNULL",
            "NULLIF",
            # NULLIFZERO / ZEROIFNULL are listed in the BigQuery
            # conditional-expressions reference docs but return
            # ``Function not found: NULLIFZERO`` /
            # ``Function not found: ZEROIFNULL`` against the live service
            # (probed 2026-05-19 via top-30 gap closure session #3e).
            # Following the ARRAY_INCLUDES_* / TIMESTAMP_FROM_UNIX_MILLIS
            # precedent (sessions #3c / #2) we omit them from the
            # inventory until BigQuery ships them so the gap-target
            # denominator stays actionable.
        )
    ),
)

_NONDETERMINISTIC_HASH: dict[str, str] = {
    "SESSION_USER": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 — "
        "session-state dependent. Exercised at the unit tier."
    ),
    "GENERATE_UUID": (
        "Excluded from the conformance corpus by ADR 0022 §1.2 — "
        "non-deterministic. Property-tested via Hypothesis for shape / "
        "uniqueness."
    ),
}

FUNCTIONS_HASH = SurfaceCategory(
    id="functions_hash",
    name="Hash / security functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_hash.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/hash_functions",
            detect=_fn(name),
            nondeterministic=name in _NONDETERMINISTIC_HASH,
            notes=_NONDETERMINISTIC_HASH.get(name, ""),
        )
        for name in (
            "FARM_FINGERPRINT",
            "MD5",
            "SHA1",
            "SHA256",
            "SHA512",
            "SESSION_USER",
            "GENERATE_UUID",
        )
    ),
)

FUNCTIONS_WINDOW = SurfaceCategory(
    id="functions_window",
    name="Window / navigation functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_window.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/navigation_functions",
            detect=_fn(name),
        )
        for name in (
            "ROW_NUMBER",
            "RANK",
            "DENSE_RANK",
            "PERCENT_RANK",
            "CUME_DIST",
            "NTILE",
            "LAG",
            "LEAD",
            "FIRST_VALUE",
            "LAST_VALUE",
            "NTH_VALUE",
            "PERCENTILE_CONT",
            "PERCENTILE_DISC",
        )
    ),
)

FUNCTIONS_INTERVAL = SurfaceCategory(
    id="functions_interval",
    name="INTERVAL / RANGE functions",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions",
    items=tuple(
        SurfaceItem(
            id=f"functions_interval.{name.lower()}",
            name=name,
            bq_docs="https://cloud.google.com/bigquery/docs/reference/standard-sql/interval_functions",
            detect=_fn(name),
        )
        for name in (
            "JUSTIFY_DAYS",
            "JUSTIFY_HOURS",
            "JUSTIFY_INTERVAL",
            "MAKE_INTERVAL",
            "RANGE",
            "RANGE_CONTAINS",
            "RANGE_END",
            "RANGE_INTERSECT",
            "RANGE_OVERLAPS",
            "RANGE_SESSIONIZE",
            "RANGE_START",
            "GENERATE_RANGE_ARRAY",
        )
    ),
)

# ---------------------------------------------------------------------------
# Wire-format / response shape
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# INFORMATION_SCHEMA — virtual catalog views
# ---------------------------------------------------------------------------
INFORMATION_SCHEMA = SurfaceCategory(
    id="information_schema",
    name="INFORMATION_SCHEMA virtual views",
    bq_docs="https://cloud.google.com/bigquery/docs/information-schema-intro",
    description=(
        "BigQuery's INFORMATION_SCHEMA family of virtual tables. The "
        "emulator's pre-translation rewriter materialises each view as "
        "an inline VALUES subquery sourced from the catalog: SCHEMATA, "
        "TABLES, COLUMNS, TABLE_OPTIONS, VIEWS, PARTITIONS, ROUTINES, "
        "MATERIALIZED_VIEWS, ROW_ACCESS_POLICIES. The ``JOBS``/``JOBS_"
        "BY_*`` family is permanently out of scope — see "
        "``out-of-scope.md#information_schemajobs-family``."
    ),
    items=(
        SurfaceItem(
            id="information_schema.schemata",
            name="INFORMATION_SCHEMA.SCHEMATA",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-schemata",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*SCHEMATA\b"),
        ),
        SurfaceItem(
            id="information_schema.tables",
            name="INFORMATION_SCHEMA.TABLES",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-tables",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*TABLES\b"),
        ),
        SurfaceItem(
            id="information_schema.columns",
            name="INFORMATION_SCHEMA.COLUMNS",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-columns",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*COLUMNS\b"),
        ),
        SurfaceItem(
            id="information_schema.table_options",
            name="INFORMATION_SCHEMA.TABLE_OPTIONS",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-table-options",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*TABLE_OPTIONS\b"),
        ),
        SurfaceItem(
            id="information_schema.views",
            name="INFORMATION_SCHEMA.VIEWS",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-views",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*VIEWS\b"),
        ),
        SurfaceItem(
            id="information_schema.partitions",
            name="INFORMATION_SCHEMA.PARTITIONS",
            bq_docs="https://cloud.google.com/bigquery/docs/information-schema-partitions",
            detect=_re(r"INFORMATION_SCHEMA\s*\.\s*PARTITIONS\b"),
        ),
    ),
)


WIRE_FORMAT = SurfaceCategory(
    id="wire_format",
    name="REST / wire-format response shapes",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/rest",
    description=(
        "Shape-level concerns about the JSON BigQuery returns. The "
        "conformance corpus diffs ``schema`` + ``rows`` against recorded "
        "baselines, so these items are exercised indirectly by every "
        "fixture; depth here measures coverage of unusual shapes "
        "(REPEATED, nested STRUCT, NULL representations)."
    ),
    items=(
        SurfaceItem(
            id="wire_format.repeated_field",
            name="REPEATED mode schema field",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableFieldSchema",
            detect=_re(r"\barray\s*<"),
            notes="REPEATED is the wire form of ARRAY<T>.",
        ),
        SurfaceItem(
            id="wire_format.nested_struct",
            name="Nested RECORD/STRUCT schema field",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#TableFieldSchema",
            detect=_re(r"\bstruct\s*<"),
        ),
        SurfaceItem(
            id="wire_format.null_row",
            name="NULL in row payload",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#response-body",
            detect=_re(r"\bnull\b"),
        ),
        SurfaceItem(
            id="wire_format.query_parameters_named",
            name='Named queryParameters (mode="named")',
            bq_docs="https://cloud.google.com/bigquery/docs/parameterized-queries#bigquery_query_parameters_via_rest-python",
            detect=_re(r'"mode"\s*:\s*"named"'),
            notes=(
                "Parameter-bound queries via ``QueryJobConfig.query_parameters``."
                " Detected by the ``parameters.json`` fixture file (P2.e)."
            ),
        ),
        SurfaceItem(
            id="wire_format.query_parameters_positional",
            name='Positional queryParameters (mode="positional")',
            bq_docs="https://cloud.google.com/bigquery/docs/parameterized-queries#bigquery_query_parameters_via_rest-python",
            detect=_re(r'"mode"\s*:\s*"positional"'),
            notes=(
                "Parameter-bound queries via ``QueryJobConfig.query_parameters``"
                " using ``?`` placeholders. Detected by ``parameters.json`` (P2.e)."
            ),
        ),
        SurfaceItem(
            id="wire_format.query_parameter_array",
            name="ARRAY queryParameter",
            bq_docs="https://cloud.google.com/bigquery/docs/parameterized-queries#array_parameters",
            detect=_re(r'"type"\s*:\s*"ARRAY"'),
            notes=(
                "``arrayType`` parameter shape. Detected by ``parameters.json``"
                " carrying an ARRAY type spec (P2.e)."
            ),
        ),
        SurfaceItem(
            id="wire_format.query_parameter_struct",
            name="STRUCT queryParameter",
            bq_docs="https://cloud.google.com/bigquery/docs/parameterized-queries#struct_parameters",
            detect=_re(r'"type"\s*:\s*"STRUCT"'),
            notes=(
                "``structTypes`` parameter shape. Detected by ``parameters.json``"
                " carrying a STRUCT type spec (P2.e)."
            ),
        ),
        SurfaceItem(
            id="wire_format.query_parameter_null",
            name="NULL-valued queryParameter",
            bq_docs="https://cloud.google.com/bigquery/docs/parameterized-queries#using_null_values",
            detect=_re(r'"value"\s*:\s*null'),
            notes=(
                "A typed parameter with no value — exercises BQ's typed-NULL"
                " binding. Emulator wraps with ``CAST(? AS T)`` to preserve"
                " the declared type through the schema renderer (P2.e)."
            ),
        ),
    ),
)

# ---------------------------------------------------------------------------
# Error categories (P3.a)
# ---------------------------------------------------------------------------
ERRORS = SurfaceCategory(
    id="errors",
    name="Error response parity",
    bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/Error",
    description=(
        "Recorded error envelopes (``error.reason`` / ``http_status`` / "
        "``message_pattern``). Coverage is owned by P3.a and the "
        "``error.json`` fixtures."
    ),
    items=(
        SurfaceItem(
            id="errors.invalid",
            name="reason=invalid (syntax / argument)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/Error",
            detect=_re(r'"reason"\s*:\s*"invalid"'),
        ),
        SurfaceItem(
            id="errors.not_found",
            name="reason=notFound",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/Error",
            detect=_re(r'"reason"\s*:\s*"notFound"'),
        ),
        SurfaceItem(
            id="errors.duplicate",
            name="reason=duplicate (already exists)",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/Error",
            detect=_re(r'"reason"\s*:\s*"duplicate"'),
        ),
        SurfaceItem(
            id="errors.access_denied",
            name="reason=accessDenied",
            bq_docs="https://cloud.google.com/bigquery/docs/reference/rest/v2/Error",
            detect=_re(r'"reason"\s*:\s*"accessDenied"'),
        ),
        # ``reason=outOfRange`` is listed in the BigQuery REST API
        # error reference but is not emit-able from a query fixture.
        # SQL-level overflow / divide-by-zero / out-of-bounds errors
        # all surface as ``reason=invalidQuery`` (probed 2026-05-19
        # via top-30 gap closure session #3e — int64 overflow,
        # division by zero, oversized GENERATE_ARRAY, OFFSET past
        # array end, and DATE arithmetic past the supported range
        # all came back as ``invalidQuery``). REST-API validation
        # errors that look numeric (``max_results.value`` overflow,
        # negative ``start_index``, sub-zero ``maxCreationTime``) all
        # surface as ``reason=invalid``. ``outOfRange`` is emitted by
        # streaming-insert / partition operations that the corpus
        # does not exercise. Following the NULLIFZERO / ZEROIFNULL
        # precedent (same session) we omit the surface from the
        # inventory until a real fixture can carry the reason.
    ),
)


# ---------------------------------------------------------------------------
# Master list — order drives matrix display order.
# ---------------------------------------------------------------------------
SURFACE: tuple[SurfaceCategory, ...] = (
    DML,
    DDL,
    QUERY,
    SCRIPTING,
    TYPES,
    FUNCTIONS_STRING,
    FUNCTIONS_NUMERIC,
    FUNCTIONS_DATETIME,
    FUNCTIONS_AGGREGATE,
    FUNCTIONS_ARRAY,
    FUNCTIONS_JSON,
    FUNCTIONS_GEOGRAPHY,
    FUNCTIONS_CONVERSION,
    FUNCTIONS_CONDITIONAL,
    FUNCTIONS_HASH,
    FUNCTIONS_WINDOW,
    FUNCTIONS_INTERVAL,
    INFORMATION_SCHEMA,
    WIRE_FORMAT,
    ERRORS,
)


def all_items() -> tuple[SurfaceItem, ...]:
    """Flatten the per-category items into one tuple, in display order."""
    return tuple(item for cat in SURFACE for item in cat.items)


__all__ = [
    "DDL",
    "DML",
    "ERRORS",
    "FUNCTIONS_AGGREGATE",
    "FUNCTIONS_ARRAY",
    "FUNCTIONS_CONDITIONAL",
    "FUNCTIONS_CONVERSION",
    "FUNCTIONS_DATETIME",
    "FUNCTIONS_GEOGRAPHY",
    "FUNCTIONS_HASH",
    "FUNCTIONS_INTERVAL",
    "FUNCTIONS_JSON",
    "FUNCTIONS_NUMERIC",
    "FUNCTIONS_STRING",
    "FUNCTIONS_WINDOW",
    "INFORMATION_SCHEMA",
    "QUERY",
    "SCRIPTING",
    "SURFACE",
    "TYPES",
    "WIRE_FORMAT",
    "SurfaceCategory",
    "SurfaceItem",
    "all_items",
]
