CREATE OR REPLACE TABLE `${DATASET}.int_part`
PARTITION BY RANGE_BUCKET(user_id, GENERATE_ARRAY(0, 100, 10))
AS
  SELECT 5 AS user_id, "a" AS s UNION ALL
  SELECT 25, "b" UNION ALL
  SELECT 55, "c" UNION ALL
  SELECT 95, "d";
