CREATE OR REPLACE TABLE `${DATASET}.sales` AS
  SELECT "US" AS country, NUMERIC '100.00' AS amount UNION ALL
  SELECT "US", NUMERIC '200.50' UNION ALL
  SELECT "EU", NUMERIC '300.75' UNION ALL
  SELECT "EU", NUMERIC '400.25' UNION ALL
  SELECT "JP", NUMERIC '500.00' UNION ALL
  SELECT "JP", NUMERIC '50.00';
