"""Hypothesis property tests for RANGE_* invariants.

* ``RANGE_CONTAINS(r, v)`` is reflexive on the open boundary:
  ``RANGE_CONTAINS(RANGE(s, e), s)`` is True (half-open ``[s, e)``).
* ``RANGE_OVERLAPS`` is commutative.
* Two disjoint ranges always have an empty intersection.
"""

from __future__ import annotations

import datetime as dt

import duckdb
from hypothesis import given, settings
from hypothesis import strategies as st
import pytest

from bqemulator.domain.result import Ok
from bqemulator.sql.translator import SQLTranslator

pytestmark = pytest.mark.property


@pytest.fixture(scope="module")
def conn() -> duckdb.DuckDBPyConnection:
    return duckdb.connect(":memory:")


@pytest.fixture(scope="module")
def translator() -> SQLTranslator:
    return SQLTranslator()


def _run(translator: SQLTranslator, conn: duckdb.DuckDBPyConnection, bq_sql: str) -> object:
    result = translator.translate(bq_sql)
    assert isinstance(result, Ok), result
    return conn.execute(result.value).fetchone()


_MIN_DATE = dt.date(1970, 1, 1)
_MAX_DATE = dt.date(2099, 12, 31)


# A well-formed half-open date range ``[start, end)`` generated by
# construction (no ``assume`` filtering) so Hypothesis never trips
# ``filter_too_much`` — every draw produces ``start < end``. Composing
# two of these in one test (commutativity) used to filter ~75% of
# inputs and triggered an intermittent ``FailedHealthCheck`` in CI.
@st.composite
def _well_formed_range(draw: st.DrawFn) -> tuple[dt.date, dt.date]:
    start = draw(st.dates(min_value=_MIN_DATE, max_value=_MAX_DATE - dt.timedelta(days=1)))
    end = draw(st.dates(min_value=start + dt.timedelta(days=1), max_value=_MAX_DATE))
    return start, end


@given(rng=_well_formed_range())
@settings(max_examples=50, deadline=None)
def test_range_contains_starts_inclusive(
    rng: tuple[dt.date, dt.date],
    translator: SQLTranslator,
    conn: duckdb.DuckDBPyConnection,
) -> None:
    """``RANGE_CONTAINS(RANGE(s, e), s)`` is True for any well-formed range."""
    start, end = rng
    sql = (
        f"SELECT RANGE_CONTAINS(RANGE(DATE '{start.isoformat()}', "
        f"DATE '{end.isoformat()}'), DATE '{start.isoformat()}')"
    )
    row = _run(translator, conn, sql)
    assert row == (True,)


@given(rng=_well_formed_range())
@settings(max_examples=50, deadline=None)
def test_range_contains_end_exclusive(
    rng: tuple[dt.date, dt.date],
    translator: SQLTranslator,
    conn: duckdb.DuckDBPyConnection,
) -> None:
    """``RANGE_CONTAINS(RANGE(s, e), e)`` is False (half-open semantics)."""
    start, end = rng
    sql = (
        f"SELECT RANGE_CONTAINS(RANGE(DATE '{start.isoformat()}', "
        f"DATE '{end.isoformat()}'), DATE '{end.isoformat()}')"
    )
    row = _run(translator, conn, sql)
    assert row == (False,)


@given(rng_a=_well_formed_range(), rng_b=_well_formed_range())
@settings(max_examples=40, deadline=None)
def test_range_overlaps_is_commutative(
    rng_a: tuple[dt.date, dt.date],
    rng_b: tuple[dt.date, dt.date],
    translator: SQLTranslator,
    conn: duckdb.DuckDBPyConnection,
) -> None:
    """``RANGE_OVERLAPS(a, b) == RANGE_OVERLAPS(b, a)`` for any well-formed pair."""
    s1, e1 = rng_a
    s2, e2 = rng_b
    sql_a = (
        f"SELECT RANGE_OVERLAPS("
        f"RANGE(DATE '{s1.isoformat()}', DATE '{e1.isoformat()}'),"
        f"RANGE(DATE '{s2.isoformat()}', DATE '{e2.isoformat()}'))"
    )
    sql_b = (
        f"SELECT RANGE_OVERLAPS("
        f"RANGE(DATE '{s2.isoformat()}', DATE '{e2.isoformat()}'),"
        f"RANGE(DATE '{s1.isoformat()}', DATE '{e1.isoformat()}'))"
    )
    a = _run(translator, conn, sql_a)
    b = _run(translator, conn, sql_b)
    assert a == b
