CREATE MATERIALIZED VIEW `${DATASET}.mv`
AS SELECT label, SUM(amount) AS total FROM `${DATASET}.t` GROUP BY label;
DROP MATERIALIZED VIEW `${DATASET}.mv`;
CREATE MATERIALIZED VIEW `${DATASET}.mv`
AS SELECT label, COUNT(*) AS n FROM `${DATASET}.t` GROUP BY label;
SELECT label, n FROM `${DATASET}.mv` ORDER BY label
