CREATE OR REPLACE TABLE `${DATASET}.users` AS
  SELECT 1 AS user_id, "alice" AS name UNION ALL
  SELECT 2, "bob" UNION ALL
  SELECT 3, "carol";
CREATE OR REPLACE TABLE `${DATASET}.orders` AS
  SELECT 1 AS user_id, 100 AS amount UNION ALL
  SELECT 1, 200 UNION ALL
  SELECT 2, 300 UNION ALL
  SELECT 3, 400 UNION ALL
  SELECT 3, 500;
