CREATE OR REPLACE TABLE `${DATASET}.orders` AS
SELECT 1 AS id, 10 AS customer_id, NUMERIC '100.00' AS amount UNION ALL
SELECT 2, 20, NUMERIC '200.00' UNION ALL
SELECT 3, 30, NUMERIC '300.00';

CREATE OR REPLACE TABLE `${DATASET}.customers` AS
SELECT 10 AS customer_id, 'Acme Inc' AS name UNION ALL
SELECT 20, 'BetaCorp' UNION ALL
SELECT 30, 'Gamma LLC';
