CREATE OR REPLACE TABLE `${DATASET}.orders` AS
SELECT 1 AS id, 10 AS customer_id, 'US' AS country, NUMERIC '100.00' AS amount UNION ALL
SELECT 2, 10, 'US', NUMERIC '200.00' UNION ALL
SELECT 3, 20, 'EU', NUMERIC '300.00' UNION ALL
SELECT 4, 30, 'JP', NUMERIC '400.00';

CREATE OR REPLACE TABLE `${DATASET}.customers` AS
SELECT 10 AS customer_id, 'Acme Inc' AS name UNION ALL
SELECT 20, 'BetaCorp' UNION ALL
SELECT 30, 'Gamma LLC';
